<a href="https://colab.research.google.com/github/lsindhungowda/Daily-report/blob/master/Day_3_Session_2_Exercises_problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a Pandas program to create and display a one-dimensional array using series  containing  event numbers upto 10000

In [ ]:
import pandas as pd
l=([i for i in range(0,10000) if i%2==0])
ds = pd.Series(l) 
print(ds)

0          0
1          2
2          4
3          6
4          8
        ... 
4995    9990
4996    9992
4997    9994
4998    9996
4999    9998
Length: 5000, dtype: int64


Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and  after convertion print its type 



In [ ]:
import pandas as pd
d = pd.Series([i for i in range(1000,2001) if i%5==0]) 
print(d)
print(d.tolist())
print(type(d.tolist()))

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
196    1980
197    1985
198    1990
199    1995
200    2000
Length: 201, dtype: int64
[1000, 1005, 1010, 1015, 1020, 1025, 1030, 1035, 1040, 1045, 1050, 1055, 1060, 1065, 1070, 1075, 1080, 1085, 1090, 1095, 1100, 1105, 1110, 1115, 1120, 1125, 1130, 1135, 1140, 1145, 1150, 1155, 1160, 1165, 1170, 1175, 1180, 1185, 1190, 1195, 1200, 1205, 1210, 1215, 1220, 1225, 1230, 1235, 1240, 1245, 1250, 1255, 1260, 1265, 1270, 1275, 1280, 1285, 1290, 1295, 1300, 1305, 1310, 1315, 1320, 1325, 1330, 1335, 1340, 1345, 1350, 1355, 1360, 1365, 1370, 1375, 1380, 1385, 1390, 1395, 1400, 1405, 1410, 1415, 1420, 1425, 1430, 1435, 1440, 1445, 1450, 1455, 1460, 1465, 1470, 1475, 1480, 1485, 1490, 1495, 1500, 1505, 1510, 1515, 1520, 1525, 1530, 1535, 1540, 1545, 1550, 1555, 1560, 1565, 1570, 1575, 1580, 1585, 1590, 1595, 1600, 1605, 1610, 1615, 1620, 1625, 1630, 1635, 1640, 1645, 1650, 1655, 1660, 1665, 1670, 1675, 1680, 1685, 1690, 1695, 1

Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [ ]:
import pandas as pd
l1=([i for i in range(1,101) if i%2==0])
l2=([i for i in range(1,100) if i%2==1])
d1=pd.Series(l1)
d2=pd.Series(l2)
print(f'Addition Of  Two Series:\n{d1+d2}')
print(f'Subtraction Of  Two Series:\n{d1-d2}')
print(f'Multiplication Of  Two Series:\n{d1*d2}')
print(f'Division Of  Two Series:\n{d1/d2}')

Addition Of  Two Series:
0       3
1       7
2      11
3      15
4      19
5      23
6      27
7      31
8      35
9      39
10     43
11     47
12     51
13     55
14     59
15     63
16     67
17     71
18     75
19     79
20     83
21     87
22     91
23     95
24     99
25    103
26    107
27    111
28    115
29    119
30    123
31    127
32    131
33    135
34    139
35    143
36    147
37    151
38    155
39    159
40    163
41    167
42    171
43    175
44    179
45    183
46    187
47    191
48    195
49    199
dtype: int64
Subtraction Of  Two Series:
0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
37    1
38    1
39    1
40    1
41    1
42    1
43    1
44    1
45    1
46    1
47    1
48    1
49    1
dtype: int64
Multiplication Of  Tw

Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.

In [ ]:
import pandas as pd
l1=([i for i in range(1,1000) if i%7==0])
l2=([i for i in range(1,1000) if i%11==0])
d1 = pd.Series(l1)
d2 = pd.Series(l2)
print("Compare the elements of the said Series:")
print("Equals:")
for i in range (len(l2)):
  print(i," ",d1[i]==d2[i])
print("Greater than:")
for i in range(len(l2)):
  print(i," ",d1[i]>d2[i])
print("Less than:")
for i in range(len(l2)):
  print(i," ",d1[i]<d2[i])

Compare the elements of the said Series:
Equals:
0   False
1   False
2   False
3   False
4   False
5   False
6   False
7   False
8   False
9   False
10   False
11   False
12   False
13   False
14   False
15   False
16   False
17   False
18   False
19   False
20   False
21   False
22   False
23   False
24   False
25   False
26   False
27   False
28   False
29   False
30   False
31   False
32   False
33   False
34   False
35   False
36   False
37   False
38   False
39   False
40   False
41   False
42   False
43   False
44   False
45   False
46   False
47   False
48   False
49   False
50   False
51   False
52   False
53   False
54   False
55   False
56   False
57   False
58   False
59   False
60   False
61   False
62   False
63   False
64   False
65   False
66   False
67   False
68   False
69   False
70   False
71   False
72   False
73   False
74   False
75   False
76   False
77   False
78   False
79   False
80   False
81   False
82   False
83   False
84   False
85   False
86   False
87  

Write a Pandas program to convert a NumPy array to a Pandas series. 

In [ ]:
import numpy as np
import pandas as pd
l1=([i for i in range(1,1001) if i%10==0])
a = np.array(l1)
print(f"NumPy array:\n{a}")
print(f"Converted Pandas series:\n{pd.Series(a)}")

NumPy array:
[  10   20   30   40   50   60   70   80   90  100  110  120  130  140
  150  160  170  180  190  200  210  220  230  240  250  260  270  280
  290  300  310  320  330  340  350  360  370  380  390  400  410  420
  430  440  450  460  470  480  490  500  510  520  530  540  550  560
  570  580  590  600  610  620  630  640  650  660  670  680  690  700
  710  720  730  740  750  760  770  780  790  800  810  820  830  840
  850  860  870  880  890  900  910  920  930  940  950  960  970  980
  990 1000]
Converted Pandas series:
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64


Write a Pandas program to convert a given Series to an array.

In [ ]:
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print(f"Original Data Series:\n{s1}")
print(f"Series to an array:\n{np.array(s1.values.tolist())}")

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array:
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


Write a Pandas program to sort a given Series.

In [ ]:
import pandas as pd
s = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print(f"Original Data Series:\n{s}")
print(pd.Series(s).sort_values())

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
0          100
1          200
2          300
6       300.12
3          400
7          400
4          500
9        great
8           is
10    language
5       python
dtype: object


Write a Pandas program to create a subsets of a given series based on value and condition.

In [ ]:
import pandas as pd
s = pd.Series(([i for i in range(1,1001) if i%10==0]))
print(f"Original Data Series:\n{s}")
print(f"Subset of the above Data Series:\n{s[s%7==0]}\n{s[s%5==0]}")


Original Data Series:
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64
Subset of the above Data Series:
6      70
13    140
20    210
27    280
34    350
41    420
48    490
55    560
62    630
69    700
76    770
83    840
90    910
97    980
dtype: int64
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64


Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000



In [ ]:
import pandas as pd
l=[2]
for v in range(3,1001):
  for n in range(2, v): 
    if (v % n) == 0: 
      break
  l.append(v)
print(l)
s = pd.Series(l)
print(f"Original Data Series:\n{s}")
print(f"Mean of the said Data Series:\n{s.mean()}")
print(f"Standard deviation of the said Data Series:\n{s.std()}")

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 

Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.
 


In [ ]:
import pandas as pd
df = pd.read_csv('movie.csv.txt')
#Display the first 10 rows
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)

First 10 rows of the DataFrame:
       gaja
0      raja
1      rani
2  rajkumar
3    googly
4     devil
5       kjf
6     jeeva
7   barjari
8     covid
9     kalla


Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields #(movie_metadata.csv file).



In [ ]:
import pandas as pd
df = pd.read_csv('movie.csv.txt')
seventh_movie = df.iloc[6]
print("Details of the seventh moviee:")
print(seventh_movie)

Details of the seventh moviee:
gaja    jeeva
Name: 6, dtype: object


Write a Pandas program to sort the DataFrame based on title_year from dataset of movie_metadata.csv for any particular three fields 

In [ ]:
import pandas as pd 
data=pd.read_csv("movies.csv") 
data.sort_values(["Year", "Name"], axis=0, 
                 ascending=True, inplace=True)  
data 

Name    Year     country Language  Unnamed: 4  Unnamed: 5
7    rajkimar  2001.0       egypt  kannada         NaN         NaN
6         kgf  2005.0      cyprus  bengali         NaN         NaN
5      googly  2006.0        cuba   marati         NaN         NaN
4       malla  2007.0     algeris     tulu         NaN         NaN
2        rani  2008.0  bangladesh   hindhi         NaN         NaN
..        ...     ...         ...      ...         ...         ...
451       NaN     NaN         NaN      NaN         NaN         NaN
452       NaN     NaN         NaN      NaN         NaN         NaN
453       NaN     NaN         NaN      NaN         NaN         NaN
454       NaN     NaN         NaN      NaN         NaN         NaN
455       NaN     NaN         NaN      NaN         NaN         NaN

[456 rows x 6 columns]

Write a Pandas program to sort the DataFrame based on country  and language from dataset of  movie_metadata.csv

In [ ]:
import pandas as pd 
data=pd.read_csv("movies.csv") 
data.sort_values(["country", "Language"], axis=0, 
                 ascending=True, inplace=True)  
data 

Name    Year     country Language  Unnamed: 4  Unnamed: 5
4     malla  2007.0     algeris     tulu         NaN         NaN
1      raja  2020.0      angola  english         NaN         NaN
3     kalla  2009.0   australia   telugu         NaN         NaN
2      rani  2008.0  bangladesh   hindhi         NaN         NaN
5    googly  2006.0        cuba   marati         NaN         NaN
..      ...     ...         ...      ...         ...         ...
451     NaN     NaN         NaN      NaN         NaN         NaN
452     NaN     NaN         NaN      NaN         NaN         NaN
453     NaN     NaN         NaN      NaN         NaN         NaN
454     NaN     NaN         NaN      NaN         NaN         NaN
455     NaN     NaN         NaN      NaN         NaN         NaN

[456 rows x 6 columns]

Write a NumPy program to generate 8 random integers between 100 and 300



In [ ]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[167 218 257 266 253 124 237 246]


Write a NumPy program to create a random integer nos of size 20 and sort it.




In [ ]:
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.25060068 0.61229126 0.5277986  0.37604367 0.68842377 0.01507103
 0.73943028 0.11730458 0.47657239 0.40721361 0.48643958 0.16978765
 0.03137074 0.40155558 0.67254978 0.62463528 0.66320582 0.17456602
 0.76329772 0.42122358]
Sorted array:
[0.01507103 0.03137074 0.11730458 0.16978765 0.17456602 0.25060068
 0.37604367 0.40155558 0.40721361 0.42122358 0.47657239 0.48643958
 0.5277986  0.61229126 0.62463528 0.66320582 0.67254978 0.68842377
 0.73943028 0.76329772]


Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.4570418  0.85605884 0.14576285 0.37123905 0.6388718  0.47327836
  0.43994374 0.96986333 0.99827394 0.30855349]
 [0.86516675 0.43691731 0.48463249 0.4634674  0.44197693 0.4036311
  0.17097674 0.62198896 0.09373348 0.22202758]
 [0.36557689 0.1537382  0.36564051 0.12546369 0.75695897 0.51142151
  0.05772205 0.01159706 0.12379927 0.44894217]
 [0.46933325 0.97375035 0.83905753 0.72234284 0.77656881 0.71323847
  0.00115449 0.82454568 0.27137091 0.32884372]
 [0.41926535 0.82425419 0.98256863 0.53497155 0.8208872  0.37643425
  0.64935031 0.67993395 0.95492557 0.75064347]
 [0.5536605  0.594245   0.44054933 0.15644724 0.79685309 0.43779021
  0.18877965 0.56672807 0.64708297 0.25737019]
 [0.40288155 0.45630228 0.87824206 0.59554012 0.52197404 0.52692781
  0.50198143 0.11437706 0.72924683 0.4039952 ]
 [0.64297693 0.13634908 0.93043998 0.52868304 0.5918696  0.74898316
  0.47609835 0.63307223 0.83070665 0.98384952]
 [0.97351191 0.02545325 0.2115219  0.28986543 0.65195947 0.809761

Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the  array and store them into a variable.

In [ ]:
import numpy as np
x = np.random.rand(4, 4)
print("Original array: ")
print(x)
y= x[:2, :3]
print("Second and third rows of the above array:")
print(y)

Original array: 
[[0.77655655 0.68840498 0.45521441 0.01413826]
 [0.5994251  0.7554162  0.4426445  0.45566866]
 [0.70396885 0.96162052 0.79116062 0.58552173]
 [0.67702821 0.64948794 0.22462329 0.16228201]]
Second and third rows of the above array:
[[0.77655655 0.68840498 0.45521441]
 [0.5994251  0.7554162  0.4426445 ]]


Write a Pandas program to get the elements of an array values into column-wise.
 


In [ ]:
import pandas as pd
l1=([i for i in range(0,1001) if i%7!=0 and i%2!=0])
l2=([i for i in range(0,1001) if i%2==0 and i%5!=0])
l3=([i for i in range(0,1001) if i%2!=0 and i%3!=0])
df = pd.DataFrame({'X':([i for i in range(0,1001) if i%7!=0 and i%2!=0]),'Y':([i for i in range(0,1001) if i%2==0 and i%5!=0]),'Z':([i for i in range(0,1001) if i%2!=0 and i%3!=0])});
df

Write a Pandas program to get the details of the movies record number divisable by 5 of the DataFrame #(movie_metadata.csv file).

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('moviees.csv')
small_df = df[['rating','budget','year']]
for i in range(1,len(df)+1):
  if i%5==0:
    print(f"{small_df.iloc[i]}\n")

rating       3
budget    80cr
year      2019
Name: 5, dtype: object

rating        5
budget    50cr 
year       2010
Name: 10, dtype: object



Write a Pandas program to find the mean and standard deviation, maximum and minimum of the data of  50 students Python marks stored in a CSV file called Python_mark.csv( you have to create the file yourself like rollno,mark for 50 records)

In [ ]:
import pandas as pd
df = pd.read_csv('Python_marks.csv')
print("file content: ",df)
print ('Mean : ' + str(df['marks'].mean()))
print ('S.D: ' + str(df['marks'].std() ))
print ('Minimum : ' + str(df['marks'].min()))
print ('Maximum : ' + strdf['marks'].max()))